try:
   risky code
except:
    hadling code


2.specific exception

try:
    a = int(input("Enter the first number:"))
    b = int(input("Enter the second number:"))
    print(a/b)
except ZeroDivisionError as e:
    print(e)
print("Program successfully completed")

3.except ---block can handle any type of exception


4.try block can have multiple except block

try:
    a = int(input("Enter the first number:"))
    b = int(input("Enter the second number:"))
    print(a/b)
except ZeroDivisionError as e:
    print("in  execpt",e)
except ValueError as e:
    print("in  execpt", e)
print("Program successfully completed")




try:
    python
    a = int(input("Enter the first number:"))
    b = int(input("Enter the second number:"))
    print(a/b)
except ZeroDivisionError as e:
    print("please enter valid input",e)
except ValueError as e:
    print("check the input it should be int", e)
except:
    print("in except")
print("Program successfully completed")




except ZeroDivisionError

except ValueError as msg

except(ZeroDivisionError,ValueError) as msg



try :

    fp = open('test1235353.json','r')
    data=fp.read()
    print(data)
except FileNotFoundError:
    print("file not found")
finally:
    try:
        fp.close()
    except NameError:
        print("Please check file object")
		
*************PEMDAS************

